from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

OUT=r'C:\Users\XiaoyanXiong\Desktop\NIDSTransformer\Defense_Speech_Script_Xiaoyan_Xiong.docx'
slides=[
("1. Title — 0:45", "Good morning, and thank you for attending my thesis defense. My thesis investigates a hierarchical time-aware Transformer for flow-level network intrusion detection. The central idea is that network traffic has two levels of temporal structure: packets form a flow, and related flows form broader behaviour. I will first introduce the basic networking concepts, then explain the two-stage model, and finally present the evaluation results, limitations, and conclusions."),
("2. Packet and flow — 1:30", "Before discussing the model, I will define two basic concepts. A packet is one transmitted unit. It contains metadata such as a timestamp, source and destination, protocol, length, and control flags. A flow groups packets that belong to the same network conversation, normally using endpoint and protocol information. A flow is therefore a sequence, while flow statistics are summaries of that sequence. Traditional flow-based detectors usually keep only the summaries. My thesis asks what is lost when packet order and timing are compressed too early."),
("3. NIDS problem — 1:20", "A network intrusion detection system monitors traffic and predicts whether activity is benign or suspicious. Signature engines such as Suricata are effective for known patterns, while learning-based systems can model broader regularities. However, there is a trade-off. Raw packets preserve detail but are expensive. Aggregate flows are scalable but remove ordering. Finally, classifying every flow independently ignores behaviours such as scanning, repeated login attempts, or coordinated connections. This motivates the research gap: packet-level structure and cross-flow context are usually studied separately."),
("4. Research questions — 1:15", "The work is organised around two questions. RQ1 asks whether a time-aware packet sequence produces a more informative representation than aggregate flow statistics alone. RQ2 asks whether historical context from related flows improves the final classification. The thesis contributes an aligned extraction pipeline, a time-aware Stage 1 encoder, a relation-aware Stage 2 model, and chronological evaluation on internal and external traffic."),
("5. Data pipeline — 1:40", "The source capture contains about 8.62 gigabytes of enterprise traffic. A custom Suricata output module extracts aligned packet and flow records in one pass. The result contains approximately 11.75 million packet rows and 421,898 flows. Only 3.945 percent of the flows have an alert-derived positive label, so accuracy alone would be misleading. Flows are sorted by start time and split chronologically into 70 percent training, 10 percent validation, and 20 percent testing. Importantly, these are weak labels: class one means that Suricata generated at least one alert in the flow; it is not independently verified attack ground truth."),
("6. Hierarchical framework — 1:10", "This figure gives the full idea in one view. Stage 1 receives the ordered packet sequence and converts it into one fixed-length embedding per flow. Stage 2 treats these flow embeddings as tokens and adds historical context before producing the final benign-or-alert-associated prediction. The hierarchy therefore respects the natural structure: packets form flows, and related flows form behaviour."),
("7. Time-aware encoding — 1:25", "Stage 1 first projects every selected packet record into the model dimension. Standard positional encoding identifies ordinal order, but it cannot distinguish microseconds from seconds. I therefore reconstruct the inter-arrival intervals, accumulate elapsed time, apply logarithmic smoothing, and combine this coordinate with packet position in a sinusoidal encoding. The ablations later compare position only, time only, both, and no encoding."),
("8. Detailed model — 1:40", "This detailed architecture shows the complete pipeline. Stage 1 uses selected packet features, time-aware encoding, a separately encoded flow-statistics branch, a masked Transformer, and hybrid attention, mean, and max pooling. Flow statistics modulate packet tokens through a bounded residual. This prevents the aggregate vector from dominating the packet pathway. Stage 2 then builds a historical context, uses the target flow as the query, gates the retrieved summary, and predicts the final probability."),
("9. Stage 2 context — 1:30", "For each target flow, Stage 2 retrieves earlier embeddings according to a relation. The tested relations are same source host, same destination host, shared endpoint, and global chronological recency. The target embedding provides one query over the historical keys and values. A learned gate controls how much context updates the current representation. I use only earlier items in stable start-time order and never retrieve historical labels. However, this is not yet strict streaming causality, because a long flow that started earlier may not have completed when the target begins."),
("10. Evaluation protocol — 1:15", "Because positive flows are rare, accuracy is not the primary metric. I emphasise macro-F1, class-one F1, average precision, false-positive rate, and absolute false-positive and false-negative counts. Checkpoints are selected using validation average precision, while the operating threshold is selected using validation class-one F1. The final test partition is used only after these choices are fixed. In the thesis logs this ranking metric is named PR-AUC, but technically it is scikit-learn average precision."),
("11. Stage 1 results — 1:25", "The Stage 1 comparison uses a common controlled test manifest. The position-plus-time Transformer achieves the strongest overall balance, with macro-F1 of 0.8882 and average precision of 0.8564. It exceeds the flow-statistics MLP, recurrent models, convolutional models, and the encoding ablations. Time-only is stronger than position-only, while using both is strongest, supporting the claim that ordinal location and elapsed time are complementary."),
("12. Fusion results — 1:20", "This ablation compares three ways to combine packet and flow information. Scheme A repeats the aggregate vector at every packet. Scheme B uses packets only. Scheme C encodes the aggregate vector once and uses bounded token modulation. Scheme C reaches macro-F1 of 0.8954 and average precision of 0.8763, while also reducing both false positives and false negatives. The careful conclusion is that a separate statistical pathway is useful; because parameter counts also change, the entire gain cannot be assigned to FiLM alone."),
("13. Relation results — 1:20", "For Stage 2, the source-host relation gives the strongest combined result. It has the highest macro-F1 and average precision and the lowest false-positive rate among the tested relations. Endpoint context recovers more positive flows, but it also generates more false positives. Global time-only context is less selective. This does not prove that source history is optimal for every attack family; binary weak labels cannot identify which attack mechanisms benefit."),
("14. Stage 2 architecture results — 1:25", "The architecture comparison fixes the Stage 1 embeddings, context relation, window, objective, and evaluation protocol. The proposed target-query model obtains macro-F1 of 0.9275, class-one F1 of 0.8610, and average precision of 0.9345. It reduces both error types compared with the vanilla Transformer. Nevertheless, the no-context head is much smaller, and other baselines are not parameter matched. The result supports the integrated architecture, but it is not a pure causal estimate of historical context alone."),
("15. External generalisation — 1:25", "External evaluation applies the source-trained model without retraining or threshold adjustment. Across five non-overlapping CICIDS2017 Wednesday windows, pooled macro-F1 is 0.8966, while individual windows range from 0.8536 to 0.9226. A separate company server capture reaches macro-F1 of 0.9026 and average precision of 0.8771. These results demonstrate useful discrimination outside the source capture, but the variation shows that transfer is not invariant across time or environment."),
("16. Conclusions and limitations — 1:35", "The evidence supports four conclusions. Packet order and elapsed time contribute complementary information. Aggregate statistics remain useful when they condition rather than replace packet evidence. Selective source-host history improves the evaluated detector. Finally, discrimination transfers to the two external sources, although unevenly. The thesis does not establish independently verified attack ground truth, strict online availability, statistical significance across seeds, or universal cross-network generalisation. These limitations define the next experiments rather than invalidating the observed results."),
("17. Takeaway — 0:45", "To conclude, network traffic is naturally hierarchical, and the detector benefits from respecting that hierarchy. Stage 1 models how a flow develops internally through packet order and elapsed time. Stage 2 asks how earlier related flows change the interpretation of the target. Together, these two levels improve alert-associated flow classification in the evaluated settings. Thank you for your attention. I welcome your questions.")]

doc=Document(); sec=doc.sections[0]; sec.top_margin=Inches(.75);sec.bottom_margin=Inches(.75);sec.left_margin=Inches(.85);sec.right_margin=Inches(.85)
styles=doc.styles; styles['Normal'].font.name='Arial';styles['Normal'].font.size=Pt(11);styles['Normal'].paragraph_format.space_after=Pt(7);styles['Normal'].paragraph_format.line_spacing=1.15
for name,size,color in [('Title',26,'111318'),('Heading 1',16,'1677B8'),('Heading 2',13,'1677B8')]:
 st=styles[name];st.font.name='Arial';st.font.size=Pt(size);st.font.color.rgb=RGBColor.from_string(color)
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;r=p.add_run('MSc Thesis Defense — Speaker Script');r.bold=True;r.font.size=Pt(26);r.font.color.rgb=RGBColor.from_string('111318')
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;r=p.add_run('A Hierarchical Time-Aware Transformer for Flow-Level Network Intrusion Detection');r.font.size=Pt(15);r.font.color.rgb=RGBColor.from_string('1677B8')
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.add_run('Xiaoyan Xiong | Target duration: approximately 23 minutes + 2 minutes buffer').italic=True
doc.add_heading('Delivery notes',level=1)
for t in ['Speak at a calm pace of about 115–125 words per minute.','Pause briefly after each result slide and point to the highlighted metric.','Use “alert-associated class” when discussing labels; avoid implying independently verified attacks.','If time is short, compress slides 8, 10 and 15 rather than skipping the final limitations.']:
 doc.add_paragraph(t,style='List Bullet')
for title,script in slides:
 doc.add_heading(title,level=1);doc.add_paragraph(script)
 q=doc.add_paragraph();q.paragraph_format.space_before=Pt(3);run=q.add_run('Transition: ')
 run.bold=True; q.add_run('Move to the next slide after the final sentence and allow a short pause.')
doc.add_heading('Likely defense questions',level=1)
qas=[('Why use Suricata labels?','They enabled deterministic large-scale weak supervision, but they are not treated as perfect ground truth. The thesis explicitly limits the claim to alert-associated behaviour.'),('Why a two-stage model instead of end-to-end training?','Freezing Stage 1 isolates intra-flow representation from Stage 2 context and makes ablations easier to attribute. End-to-end optimisation is future work.'),('Is Stage 2 truly causal?','It is causal in stable flow-start order and excludes future items and labels. It is not strict streaming availability causality because earlier long-lived flows may not have completed.'),('Why is source-host context best?','It is the strongest observed relation for this capture, plausibly because repeated outbound activity preserves scanning or retry patterns. Binary labels cannot prove the mechanism.'),('Why macro-F1 and average precision?','The positive prevalence is low. Macro-F1 weights both classes equally, while average precision focuses on ranking the positive class.'),('Can the results generalise?','External tests show useful transfer to CICIDS2017 windows and another server, but performance varies. The evidence is preliminary rather than universal.')]
for q,a in qas:
 p=doc.add_paragraph();r=p.add_run(q);r.bold=True;r.font.color.rgb=RGBColor.from_string('1677B8');doc.add_paragraph(a)
doc.save(OUT)
print(OUT)
